name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - attr=2.5.1=h166bdaf_1
  - aws-c-auth=0.6.27=he072965_1
  - aws-c-cal=0.5.26=hf677bf3_1
  - aws-c-common=0.8.19=hd590300_0
  - aws-c-compression=0.2.16=hbad4bc6_7
  - aws-c-event-stream=0.2.20=hb4b372c_7
  - aws-c-http=0.7.7=h2632f9a_4
  - aws-c-io=0.13.21=h9fef7b8_5
  - aws-c-mqtt=0.8.11=h2282364_1
  - aws-c-s3=0.3.0=hcb5a9b2_2
  - aws-c-sdkutils=0.1.9=hbad4bc6_2
  - aws-checksums=0.1.14=hbad4bc6_7
  - aws-crt-cpp=0.20.2=he0fdcb3_0
  - aws-sdk-cpp=1.10.57=h059227d_13
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blosc=1.21.4=h0f2a231_0
  - brotli-bin=1.0.9=h166bdaf_8
  - brotli-python=1.0.9=py311ha362b79_8
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cairo=1.16.0=hbbf8b49_1016
  - curl=8.1.2=h409715c_0
  - dask-core=2023.7.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - expat=2.5.0=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=hac7e632_2
  - freetype=2.12.1=hca18f0e_1
  - geos=3.11.2=hcb278e6_0
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - glib=2.76.3=hfc55251_0
  - glib-tools=2.76.3=hfc55251_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h58526e2_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.3=h938bd60_1
  - gstreamer=1.22.3=h977cf35_1
  - harfbuzz=7.3.0=hdb3a94d_0
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.0=nompi_hb72d44e_103
  - icu=72.1=hcb278e6_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.0=pyhd8ed1ab_0
  - ipython_genutils=0.2.0=py_1
  - jasper=4.0.0=h32699f2_1
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py311h38be061_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.7.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.8=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.2=cxx17_h59595ed_2
  - libaec=1.0.6=hcb278e6_1
  - libarrow=12.0.0=h96638e8_3_cpu
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=15.0.7=default_h7634d5b_2
  - libclang13=15.0.7=default_h9986a30_2
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.1.2=h409715c_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=h3358134_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.76.3=hebfc3b9_0
  - libglu=9.0.0=hac7e632_1002
  - libgomp=12.2.0=h65d4601_19
  - libgoogle-cloud=2.10.1=hac9eb74_1
  - libgpg-error=1.46=h620e276_0
  - libgrpc=1.54.2=hb20ce57_2
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm15=15.0.7=h5cf9203_2
  - libnetcdf=4.9.2=nompi_h0f3d0bb_105
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libnuma=2.0.16=h0b41bf4_1
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hbcd7760_1
  - libprotobuf=3.21.12=h3eb15da_0
  - libsndfile=1.2.0=hb75c966_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=253=h8c4010b_1
  - libthrift=0.18.1=h8fd135c_1
  - libtiff=4.5.0=ha587672_6
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.4=h0d562d8_0
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=h166bdaf_4
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib-base=3.7.1=py311h8597a09_0
  - mpg123=1.31.3=hcb278e6_0
  - msgpack-python=1.0.5=py311ha3edf6b_0
  - mysql-common=8.0.32=hf1915f5_2
  - mysql-libs=8.0.32=hca2cd23_2
  - nbconvert-core=7.6.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.6.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.1=hd590300_1
  - orc=1.8.3=hfdbbad2_0
  - pandoc=3.1.2=h32600fe_1
  - pcre2=10.40=hc3806b6_0
  - pixman=0.40.0=h36c2ea0_0
  - proj=9.2.0=h8ffa02c_0
  - prometheus_client=0.17.0=pyhd8ed1ab_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio-client=16.1=hb77b528_4
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyqt=5.15.7=py311ha74522f_3
  - python=3.11.3=h2755cc3_0_cpython
  - python-eccodes=1.5.1=py311hcb2cf0a_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - qt-main=5.15.8=h01ceb2d_13
  - qtconsole-base=5.4.3=pyha770c72_0
  - rdma-core=28.9=h59595ed_1
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - s2n=1.3.44=h06160fa_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - snappy=1.1.10=h9fff704_0
  - sqlite=3.42.0=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - ucx=1.14.1=hf587318_1
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h8ee46fc_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - anyio==3.7.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.2.1
    - attrs==23.1.0
    - backcall==0.2.0
    - backports-functools-lru-cache==1.6.5
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - bokeh==3.2.0
    - brotli==1.0.9
    - cartopy==0.21.1
    - certifi==2023.5.7
    - cffi==1.15.1
    - cfgrib==0.9.10.4
    - cftime==1.6.2
    - charset-normalizer==3.2.0
    - click==8.1.4
    - cloudpickle==2.2.1
    - comm==0.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - cytoolz==0.12.0
    - dask==2023.7.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distributed==2023.7.0
    - eccodes==1.5.1
    - entrypoints==0.4
    - exceptiongroup==1.1.2
    - executing==1.2.0
    - fastjsonschema==2.17.1
    - findlibs==0.0.5
    - flit-core==3.9.0
    - fonttools==4.39.4
    - fsspec==2023.6.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.0
    - ipykernel==6.24.0
    - ipympl==0.9.3
    - ipython==8.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.7
    - jedi==0.18.2
    - jinja2==3.1.2
    - jsonschema==4.18.0
    - jsonschema-specifications==2023.6.1
    - jupyter==1.0.0
    - jupyter-client==8.3.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.7.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.8
    - kiwisolver==1.4.4
    - locket==1.0.0
    - lz4==4.3.2
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mistune==3.0.0
    - msgpack==1.0.5
    - munkres==1.1.4
    - nbclassic==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.6.0
    - nbformat==5.9.0
    - nest-asyncio==1.5.6
    - netcdf4==1.6.3
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.24.3
    - overrides==7.3.1
    - packaging==23.1
    - pandas==2.0.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - partd==1.4.0
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - pip==23.1.2
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.8.1
    - ply==3.11
    - pooch==1.7.0
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.39
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==12.0.0
    - pycparser==2.21
    - pygments==2.15.1
    - pyparsing==3.1.0
    - pyproj==3.5.0
    - pyqt5==5.15.7
    - pyqt5-sip==12.11.0
    - pyshp==2.3.1
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.1.0
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - referencing==0.29.1
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.7.1
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - setuptools==68.0.0
    - shapely==2.0.1
    - sip==6.7.9
    - six==1.16.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.2
    - statsmodels==0.14.0
    - tblib==1.7.0
    - terminado==0.17.1
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - tornado==6.3.2
    - traitlets==5.9.0
    - typing-extensions==4.7.1
    - typing-utils==0.1.0
    - tzdata==2023.3
    - urllib3==2.0.3
    - wcwidth==0.2.6
    - webencodings==0.5.1
    - websocket-client==1.6.1
    - wheel==0.40.0
    - widgetsnbextension==4.0.8
    - xarray==2023.6.0
    - xyzservices==2023.5.0
    - zict==3.0.0
    - zipp==3.15.0
prefix: /home/pd423/.conda/envs/mamba/envs/phd_ph6-02_ens-extended_analysis

